# Specify the version for docker-compose.yml
version: "3.8"

# add the services needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=rollic
      - POSTGRES_PASSWORD=rollic
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rollic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rollic
      - POSTGRES_SSL_DISABLE=true
      - MIGRATION_FOLDER=file://db/migrations
      - DEBUG=true
      - BOIL_DEBUG=false
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=local
      - CONTEXT_TIMEOUT=10

    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"
    ports:
      - "8888:8080"

volumes:
  dbdata: # create the volume for persisting data.
            