// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/h4yfans/case-study/domain"
	mock "github.com/stretchr/testify/mock"

	models "github.com/h4yfans/case-study/models"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, user
func (_m *UserUsecase) Create(c context.Context, user *models.User) (*domain.UserResponse, error) {
	ret := _m.Called(c, user)

	var r0 *domain.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *domain.UserResponse); ok {
		r0 = rf(c, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c, id
func (_m *UserUsecase) Delete(c context.Context, id int) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUser provides a mock function with given fields: c
func (_m *UserUsecase) GetAllUser(c context.Context) ([]domain.UserResponse, error) {
	ret := _m.Called(c)

	var r0 []domain.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context) []domain.UserResponse); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *UserUsecase) GetByID(c context.Context, id int) (*domain.UserResponse, error) {
	ret := _m.Called(c, id)

	var r0 *domain.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.UserResponse); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, user
func (_m *UserUsecase) Update(c context.Context, user *models.User) (*domain.UserResponse, error) {
	ret := _m.Called(c, user)

	var r0 *domain.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *domain.UserResponse); ok {
		r0 = rf(c, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
